theme: jekyll-theme-cayman
title: 02806 Project
subtitle: The polarizing culture of Yelp and guidance for getting by as a business owner
description: Analysis of Yelp data around businesses and reviews through the lens of Austin, Texas 
